# CI 项目
name: AutoUpdate

# CI 权限
permissions: write-all

# CI 计划
on:
  # 自动运行: 每天早上 3 点
  schedule:
    - cron: 0 19 * * *
  # 手动运行
  workflow_dispatch:
    inputs:
      COMMIT:
        description: 'Commit Message'
        required: false
        type: string
        default: ''

# CI 环境
env:
  # GITHUB ENV
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  # WRT ENV
  WRT_COMMIT: ${{inputs.COMMIT}}

# CI 任务
jobs:
  auto-update:
    name: ZeroDreamCI
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutProject
        uses: actions/checkout@main
        with:
          token: ${{secrets.WORKFLOW_TOKEN}}

      - name: InitZeroDreamCI
        run: |
          ZeroDreamCiPath="$RUNNER_TEMP/ZeroDreamCI-$(uuidgen | tr -d '-')"
          git clone --depth=1 https://github.com/zero-dream/ZeroDream-CI.git "$ZeroDreamCiPath/"
          chmod +x "$ZeroDreamCiPath/ZeroDream/Main/Init.sh"
          source "$ZeroDreamCiPath/ZeroDream/Main/Init.sh"
          # --------------------------------------------------
          source "$ZD_ScriptLibPath/Hook.sh"
          hook 'AutoUpdate/InitZeroDreamCI'

      - name: AutoUpdate
        run: |
          # Source
          source "$ZD_ScriptLibPath/CreateTempPath.sh"
          source "$ZD_ScriptLibPath/GitPush.sh"
          # GitClone
          autoUpdatePath=$(createTempPath 'AutoUpdate')
          git clone --depth=1 https://github.com/$GITHUB_REPOSITORY.git "$autoUpdatePath/"
          firmwareCiPath=$(createTempPath 'ZeroWrtFirmwareCI')
          git clone --depth=1 https://github.com/zero-dream/ZeroWrt-Firmware-CI.git "$firmwareCiPath/"
          # CopyFile
          copyWorkflowArr=('CleanCache' 'CompileZeroWrt' 'TestZeroWrt' 'ZeroWrtCore')
          for fileName in "${copyWorkflowArr[@]}"; do
            cp -r "$firmwareCiPath/.github/workflows/$fileName.yml" "$autoUpdatePath/"
          done
          # PushFile
          gitPush "${{github.ref}}" "$autoUpdatePath" ""
          # DeleteRepo
          rm -rf "$autoUpdatePath/"
          rm -rf "$firmwareCiPath/"
